### ISSUE TITLE
Unnecessary files; `.DS_Store`

### ISSUE THREAD

**Issue by JinraeKim** [nhcho91/FlightGNC.jl#1]
Files whose names are `.DS_Store` seems to be included in every directory.

**Comment by nhcho91** [comment]
Thank you for letting me know. 
Now it's removed and included in .gitignore.

**Comment by JinraeKim** [comment]
@nhcho91
It seems still be unresolved. See #2 .

**Comment by nhcho91** [comment]
The files that are not relevant to the project are now removed.
