### ISSUE TITLE
[Suggestion] the role of this package; road map

### ISSUE THREAD

**Issue by JinraeKim** [nhcho91/FlightGNC.jl#3]
# Issue
I think that the current functionality of this package seems too similar to that of [FlightSims.jl](https://github.com/JinraeKim/FlightSims.jl).

# Suggestion
IMO, it's possible that this package exports only the core functionality of some FlightGNC stuffs (that you intended, perhaps guidance laws?) construct some off-the-shelf FlightSIms.jl-like Envs and Controllers using the core functionality of FlightGNC.jl in a new package, namely, FSImEnvs.jl.

For example, suppose that the following stuffs are ready-to-export in this package as
```julia
function dynamics_missile(p, v, u)
    # p_dot = ...
    p_dot, v_dot
end

function command_BPNG(p_M, v_M, something-like-them)
    # some appropriate outputs
end
```

and in `FSimEnvs.jl`, we may construct a FSim-like envs and controllers as the following.

```julia
struct MissileEnv <: AbstractEnv  # FSimBase-dependent
    # some-parameters-we-need
end
function Dynamics!(env::MissileEnv)
    @Loggable function dynamics!(dx, x, params, t; u)
        @unpack p, v = dx
        p_dot, v_dot = FlightGNC.dynamics_missile(p, v, u)
        dx.p = p_dot
        dx.v = v_dot
    end
end

abstract type MissileGuidance <: AbstractController  # FSimBase-dependent
struct  BPNG <: MissileGuidance
    # blahblah...
end
function Command(BPNG)  # FSimBase-dependent
    # blahblah...
end
```

Then, import `FSimEnvs.jl` in `FlightSims.jl`!

# Notes
## Why is it necessary?
- This package can be a package independent of FlightSims.jl. It makes this package reusable regardless of users' simulator preference.
- Also, there may be no big difference between [FlightSims.jl](https://github.com/JinraeKim/FlightSims.jl) and this package, which would be exhausting.

## One more thing...
- Of course, it's a suggestion. The code structure and road map of this package depend on you :)

**Comment by JinraeKim** [comment]
The point is:
how about making this package a general-purpose flight GNC library and considering FlightSims.jl as a simulator?

**Comment by nhcho91** [comment]
Thank you for your suggestion.
I have been aware of the dependency of current code to FlightSims.jl (and FSimBase.jl).
I will take your suggestion seriously, and apply suggested changes in the future.
